language: ruby
rvm:
  - 2.0.0
notifications:
  hipchat:
    rooms:
      secure: "dPDcvtGQXXzdj31ftZkRShrn+l1TCnTEPTdr6YVAfzAI1Ashzhr4yGvnNfMs\n4lbxYDJfRxpTO5Xd1Hte5HH7c0ijoHEGjajySSl43+nLeShw+CWhuxKSbmCM\nnICGbjLhNPSDTIg1QPO/AkUCF3YG6szmd3JX9XLathUrt0HOBTY="
    on_success: change
    on_failure: change
  recipients:
    - jari@holderdeord.no
script:
  - script/lint
