language: ruby
rvm:
  - 1.8.7
notifications:
  hipchat:
    rooms:
      secure: "dPDcvtGQXXzdj31ftZkRShrn+l1TCnTEPTdr6YVAfzAI1Ashzhr4yGvnNfMs\n4lbxYDJfRxpTO5Xd1Hte5HH7c0ijoHEGjajySSl43+nLeShw+CWhuxKSbmCM\nnICGbjLhNPSDTIg1QPO/AkUCF3YG6szmd3JX9XLathUrt0HOBTY="
    on_success: change
    on_failure: change
  recipients:
    - jari@holderdeord.no
  irc:
    channels:
      - "irc.freenode.net#holderdeord"
    on_success: change
    on_failure: change
    template:
      - "%{author} | %{commit} | %{message} | %{build_url}"
script:
  - script/lint
