#!/bin/bash

output=$(/sbin/status statsd)
echo $output | grep 'running' > /dev/null 2>&1

retcode=$?

if [ $retcode -gt 0 ]
then
  echo "statsd: FAILED "
  exit 2
else
  echo "statsd: OK "
  exit 0
fi
