#!/bin/bash

[ -n "$DEBUG" ] && set -x


ROOT="$(dirname $0)/.."

# Make sure we have bundler
gem spec bundler -v '~> 1.0' > /dev/null 2>&1

if [[ "$?" != "0" ]]; then
  if ruby -rubygems -e 'Gem.path.any? { |e| File.writable?(e) } or exit 1'; then
    gem install --no-rdoc --no-ri bundler
  else
    sudo gem install --no-rdoc --no-ri bundler
  fi
fi

set -e

# Add pre-commit lint if we're in a git repo
if [[ -d "${ROOT}/.git" ]]; then
  hook="${ROOT}/.git/hooks/pre-commit"

  if [[ ! -x $hook ]]; then
    cat > $hook <<END
  #!/bin/sh
  $(pwd)/script/lint
END

    chmod +x $hook
  fi
fi

# We don't want old config hanging around.
rm -rf .bundle/config
rm -rf .librarian/puppet/config

# Bundle install unless we're already up to date.
bundle install --binstubs bin --path .bundle --quiet "$@"

# Install third-party puppet modules
${ROOT}/bin/librarian-puppet install --path=third-party