#!/bin/bash

ROOT="$(dirname $0)/.."

${ROOT}/script/bootstrap || abort "unable to bootstrap"
${ROOT}/bin/puppet parser validate $(find hdo-modules/ -name "*.pp") || exit 1

for mod in ${ROOT}/hdo-modules/*
do
  echo -n "checking `basename ${mod}`..."

  ${ROOT}/bin/puppet-lint --log-format "%{fullpath}:%{linenumber} %{KIND} %{message}" \
    --no-documentation-check \
    --no-80chars-check \
    --no-class_inherits_from_params_class-check \
    --fail-on-warnings \
    "${mod}"

  ret=$?

  if [[ "${ret}" == "0" ]]; then
    echo "ok"
  else
    echo "failed"
  fi

  [[ "${code}" != "1" ]] && code="${ret}"
done

exit "${code}"
