#!/bin/bash

ROOT="$(dirname $0)/.."

${ROOT}/script/bootstrap || abort "unable to bootstrap"
${ROOT}/bin/puppet parser validate $(find modules/ -name "*.pp") || exit 1

${ROOT}/bin/puppet-lint --log-format "%{fullpath}:%{linenumber} %{KIND} %{message}" \
  --no-documentation-check \
  --no-80chars-check \
  --no-class_inherits_from_params_class-check \
  --fail-on-warnings \
  modules/
