#!/bin/bash

if [[ "$#" -eq 0 || "$#" > 2 ]]; then
  echo "USAGE: $0 [server] [puppet args]"
  exit 65
fi

SERVER=$1
shift
COMMAND="sudo puppet agent --test $*"

user="${HDO_USER:=$USER}"

echo "Running puppet @ ${SERVER}: ${COMMAND}"
ssh -t "${user}@${SERVER}.holderdeord.no" $COMMAND

