#
# This file is managed by Puppet. Local edits will be lost.
#

<%= scope.lookupvar('hdo::params::environment') %>:
  adapter: postgresql
  encoding: unicode
  database: hdo_<%= scope.lookupvar('hdo::params::environment') %>
  pool: 5
  username: <%= scope.lookupvar('hdo::params::db_username') %>
  password: <%= scope.lookupvar('hdo::params::db_password') %>
  <%- if @db_host -%>
  host: <%= scope.lookupvar('db_host') %>
  <%- end -%>
  <%- if @db_port -%>
  port: <%= scope.lookupvar('db_port') %>
  <%- end -%>
