#!/bin/bash

output=$(GET -dS -t 5  http://localhost:9200)
echo $output | grep '200 OK' > /dev/null 2>&1

retcode=$?

if [ $retcode -gt 0 ]
then
  echo "elasticsearch: FAILED "
  exit 2
else
  echo "elasticsearch: OK "
  exit 0
fi

